/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'

const TerminosLazyRouteImport = createFileRoute('/terminos')()
const RegisterLazyRouteImport = createFileRoute('/register')()
const RecuperarContrasenaLazyRouteImport = createFileRoute(
  '/recuperar-contrasena',
)()
const ProfileLazyRouteImport = createFileRoute('/profile')()
const PrivacidadLazyRouteImport = createFileRoute('/privacidad')()
const MapLazyRouteImport = createFileRoute('/map')()
const LoginLazyRouteImport = createFileRoute('/login')()
const FavoritesLazyRouteImport = createFileRoute('/favorites')()
const FaqLazyRouteImport = createFileRoute('/faq')()
const ConfigLazyRouteImport = createFileRoute('/config')()
const AcercaLazyRouteImport = createFileRoute('/acerca')()
const IndexLazyRouteImport = createFileRoute('/')()

const TerminosLazyRoute = TerminosLazyRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/terminos.lazy').then((d) => d.Route))
const RegisterLazyRoute = RegisterLazyRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))
const RecuperarContrasenaLazyRoute = RecuperarContrasenaLazyRouteImport.update({
  id: '/recuperar-contrasena',
  path: '/recuperar-contrasena',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/recuperar-contrasena.lazy').then((d) => d.Route),
)
const ProfileLazyRoute = ProfileLazyRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))
const PrivacidadLazyRoute = PrivacidadLazyRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/privacidad.lazy').then((d) => d.Route))
const MapLazyRoute = MapLazyRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/map.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const FavoritesLazyRoute = FavoritesLazyRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/favorites.lazy').then((d) => d.Route))
const FaqLazyRoute = FaqLazyRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/faq.lazy').then((d) => d.Route))
const ConfigLazyRoute = ConfigLazyRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/config.lazy').then((d) => d.Route))
const AcercaLazyRoute = AcercaLazyRouteImport.update({
  id: '/acerca',
  path: '/acerca',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/acerca.lazy').then((d) => d.Route))
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminRoute
  '/acerca': typeof AcercaLazyRoute
  '/config': typeof ConfigLazyRoute
  '/faq': typeof FaqLazyRoute
  '/favorites': typeof FavoritesLazyRoute
  '/login': typeof LoginLazyRoute
  '/map': typeof MapLazyRoute
  '/privacidad': typeof PrivacidadLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaLazyRoute
  '/register': typeof RegisterLazyRoute
  '/terminos': typeof TerminosLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminRoute
  '/acerca': typeof AcercaLazyRoute
  '/config': typeof ConfigLazyRoute
  '/faq': typeof FaqLazyRoute
  '/favorites': typeof FavoritesLazyRoute
  '/login': typeof LoginLazyRoute
  '/map': typeof MapLazyRoute
  '/privacidad': typeof PrivacidadLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaLazyRoute
  '/register': typeof RegisterLazyRoute
  '/terminos': typeof TerminosLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminRoute
  '/acerca': typeof AcercaLazyRoute
  '/config': typeof ConfigLazyRoute
  '/faq': typeof FaqLazyRoute
  '/favorites': typeof FavoritesLazyRoute
  '/login': typeof LoginLazyRoute
  '/map': typeof MapLazyRoute
  '/privacidad': typeof PrivacidadLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaLazyRoute
  '/register': typeof RegisterLazyRoute
  '/terminos': typeof TerminosLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/acerca'
    | '/config'
    | '/faq'
    | '/favorites'
    | '/login'
    | '/map'
    | '/privacidad'
    | '/profile'
    | '/recuperar-contrasena'
    | '/register'
    | '/terminos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/acerca'
    | '/config'
    | '/faq'
    | '/favorites'
    | '/login'
    | '/map'
    | '/privacidad'
    | '/profile'
    | '/recuperar-contrasena'
    | '/register'
    | '/terminos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/acerca'
    | '/config'
    | '/faq'
    | '/favorites'
    | '/login'
    | '/map'
    | '/privacidad'
    | '/profile'
    | '/recuperar-contrasena'
    | '/register'
    | '/terminos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AdminRoute: typeof AdminRoute
  AcercaLazyRoute: typeof AcercaLazyRoute
  ConfigLazyRoute: typeof ConfigLazyRoute
  FaqLazyRoute: typeof FaqLazyRoute
  FavoritesLazyRoute: typeof FavoritesLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  MapLazyRoute: typeof MapLazyRoute
  PrivacidadLazyRoute: typeof PrivacidadLazyRoute
  ProfileLazyRoute: typeof ProfileLazyRoute
  RecuperarContrasenaLazyRoute: typeof RecuperarContrasenaLazyRoute
  RegisterLazyRoute: typeof RegisterLazyRoute
  TerminosLazyRoute: typeof TerminosLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-contrasena': {
      id: '/recuperar-contrasena'
      path: '/recuperar-contrasena'
      fullPath: '/recuperar-contrasena'
      preLoaderRoute: typeof RecuperarContrasenaLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acerca': {
      id: '/acerca'
      path: '/acerca'
      fullPath: '/acerca'
      preLoaderRoute: typeof AcercaLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AdminRoute: AdminRoute,
  AcercaLazyRoute: AcercaLazyRoute,
  ConfigLazyRoute: ConfigLazyRoute,
  FaqLazyRoute: FaqLazyRoute,
  FavoritesLazyRoute: FavoritesLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  MapLazyRoute: MapLazyRoute,
  PrivacidadLazyRoute: PrivacidadLazyRoute,
  ProfileLazyRoute: ProfileLazyRoute,
  RecuperarContrasenaLazyRoute: RecuperarContrasenaLazyRoute,
  RegisterLazyRoute: RegisterLazyRoute,
  TerminosLazyRoute: TerminosLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
